const { PrismaClient } = require("../generated/prisma");
const prisma = new PrismaClient();


const phoneImages = {
  "Samsung Galaxy S25 Ultra": "https://images.samsung.com/is/image/samsung/p6pim/in/2401/gallery/in-galaxy-s24-ultra-s928-sm-s928bztqins-thumb-539573190",
  "Samsung Galaxy Z Fold 6": "https://images.samsung.com/is/image/samsung/p6pim/in/2407/gallery/in-galaxy-z-fold6-f956-sm-f956bzkainu-thumb-542382265",
  "Samsung Galaxy S24 Ultra": "https://images.samsung.com/is/image/samsung/p6pim/in/2401/gallery/in-galaxy-s24-ultra-s928-sm-s928bztuins-thumb-539573163",
  "Samsung Galaxy S24+": "https://images.samsung.com/is/image/samsung/p6pim/in/2401/gallery/in-galaxy-s24-plus-s926-sm-s926bzvcins-thumb-539566424",
  "Samsung Galaxy A55 5G": "https://images.samsung.com/is/image/samsung/p6pim/in/2403/gallery/in-galaxy-a55-5g-a556-sm-a556elvcins-thumb-540776381",
  "Samsung Galaxy A35 5G": "https://images.samsung.com/is/image/samsung/p6pim/in/2403/gallery/in-galaxy-a35-5g-a356-sm-a356elbvins-thumb-540776316",
  "Samsung Galaxy Z Flip 6": "https://images.samsung.com/is/image/samsung/p6pim/in/2407/gallery/in-galaxy-z-flip6-f741-sm-f741blbainu-thumb-542382088",
  "Samsung Galaxy A06": "https://images.samsung.com/is/image/samsung/p6pim/in/2409/gallery/in-galaxy-a06-a065-sm-a065flbdins-thumb-543185430",
  "iPhone 15 Pro Max": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-max-naturaltitanium-select?wid=470&hei=556&fmt=png-alpha&.v=1692895635893",
  "iPhone 16": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-ultramarine-select?wid=470&hei=556&fmt=png-alpha&.v=1723752527114",
  "iPhone 16 Plus": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-plus-ultramarine-select?wid=470&hei=556&fmt=png-alpha&.v=1723752527105",
  "iPhone 16 Pro": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-pro-blacktitanium-select?wid=470&hei=556&fmt=png-alpha&.v=1723752775462",
  "iPhone 16 Pro Max": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-pro-max-blacktitanium-select?wid=470&hei=556&fmt=png-alpha&.v=1723752775462",
  "iPhone 13 Pro": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-alpinegreen-select?wid=470&hei=556&fmt=png-alpha&.v=1645572315986",
  "iPhone 14 Pro Max": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-max-deeppurple-select?wid=470&hei=556&fmt=png-alpha&.v=1660753056146",
  "iPhone 15": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pink-select?wid=470&hei=556&fmt=png-alpha&.v=1692895624552",
  "iPhone 15 Plus": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-plus-pink-select?wid=470&hei=556&fmt=png-alpha&.v=1692895624626",
  "iPhone 15 Pro": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-naturaltitanium-select?wid=470&hei=556&fmt=png-alpha&.v=1692895635893",
  "iPhone 14": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-purple-select?wid=470&hei=556&fmt=png-alpha&.v=1661027788150",
  "iPhone 14 Plus": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-plus-purple-select?wid=470&hei=556&fmt=png-alpha&.v=1661027788150",
  "iPhone 13": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pink-select-2021?wid=470&hei=556&fmt=png-alpha&.v=1629842709000",
  "Nothing Phone (2)": "https://assets.nothing.tech/catalog/product/cache/1/image/1600x/17f82f742ffe127f42dca9de82fb58b1/p/h/phone-2-white_3.png",
  "Nothing Phone (2a)": "https://assets.nothing.tech/catalog/product/cache/1/image/1600x/17f82f742ffe127f42dca9de82fb58b1/p/h/phone-2a-white_1.png",
  "Nothing Phone (1)": "https://assets.nothing.tech/catalog/product/cache/1/image/1600x/17f82f742ffe127f42dca9de82fb58b1/p/h/phone-1-white_2.png",
  "OnePlus 12": "https://oasis.opstatics.com/content/dam/oasis/page/2023/global/product/oneplus-12/images/kv/12-5g-green_kv.png",
  "OnePlus 11 5G": "https://oasis.opstatics.com/content/dam/oasis/page/2023/global/product/oneplus-11/images/kv/11-5g-black_kv.png",
  "OnePlus Nord CE 4": "https://oasis.opstatics.com/content/dam/oasis/page/2024/global/product/nord-ce4/images/kv/nord-ce4-celadon-marble_kv.png",
  "OnePlus 12R": "https://oasis.opstatics.com/content/dam/oasis/page/2024/global/product/oneplus-12r/images/kv/12r-5g-blue_kv.png",
  "OnePlus Nord 3 5G": "https://oasis.opstatics.com/content/dam/oasis/page/2023/global/product/nord-3/images/kv/nord-3-5g-green_kv.png",
  "Vivo X200 Pro": "https://www.vivo.com/content/dam/vivo/global/product/x200-pro/gallery/X200-Pro-Titanium-Gray_1.png",
  "Vivo X100 Pro": "https://www.vivo.com/content/dam/vivo/in/product/x100-pro/gallery/X100-Pro-Asteroid-Black_1.png",
  "Vivo V30 Pro": "https://www.vivo.com/content/dam/vivo/in/product/v30-pro/gallery/V30-Pro-Andaman-Blue_1.png",
  "Vivo V30": "https://www.vivo.com/content/dam/vivo/in/product/v30/gallery/V30-Andaman-Blue_1.png",
  "Vivo V40 Pro": "https://www.vivo.com/content/dam/vivo/in/product/v40-pro/gallery/V40-Pro-Ganges-Blue_1.png",
  "Vivo V40": "https://www.vivo.com/content/dam/vivo/in/product/v40/gallery/V40-Ganges-Blue_1.png",
  "Vivo T3 Pro": "https://www.vivo.com/content/dam/vivo/in/product/t3-pro/gallery/T3-Pro-Sandstone-Orange_1.png",
  "Vivo T3": "https://www.vivo.com/content/dam/vivo/in/product/t3/gallery/T3-Crystal-Flake_1.png",
  "Xiaomi 14": "https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1704787456.44907933.png",
  "Realme GT 6": "https://image01.realme.net/general/20240620/1718874126694784c23a5374b4e1595565a096ab909e2.png.webp",
  "Oppo Reno 12 Pro": "https://image.oppo.com/content/dam/oppo/product-asset-library/smartphone/reno12-pro-5g/overview/reno12-pro-5g-sunset-gold-front-back.png"
};

async function main() {
  await prisma.product.createMany({
    data: [

      {
        name: "Samsung Galaxy S25 Ultra",
        brand: "Samsung",
        specs: {
          processor: "Snapdragon 8 Gen 3",
          ram: "12GB",
          storage: "512GB",
          display: "6.8 inch Dynamic AMOLED 2X",
          camera: "200MP + 50MP + 10MP + 12MP",
          frontCamera: "12MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 123499,
        rating: 4.8,
        imageUrl: phoneImages["Samsung Galaxy S25 Ultra"],
        affiliateLink: "https://www.flipkart.com/samsung-galaxy-s25-ultra",
      },
      {
        name: "Samsung Galaxy Z Fold 6",
        brand: "Samsung",
        specs: {
          processor: "Snapdragon 8 Gen 3",
          ram: "12GB",
          storage: "256GB",
          display: "7.6 inch Foldable Dynamic AMOLED 2X",
          camera: "50MP + 12MP + 10MP",
          frontCamera: "10MP + 4MP",
          battery: "4400mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 109785,
        rating: 4.7,
        imageUrl: phoneImages["Samsung Galaxy Z Fold 6"],
        affiliateLink: "https://www.amazon.in/samsung-galaxy-z-fold6",
      },


      {
        name: "iPhone 15 Pro Max",
        brand: "Apple",
        specs: {
          processor: "A17 Pro Bionic",
          ram: "8GB",
          storage: "256GB",
          display: "6.7 inch Super Retina XDR OLED",
          camera: "48MP + 12MP + 12MP",
          frontCamera: "12MP",
          battery: "4422mAh",
          os: "iOS 17",
          network: "5G",
        },
        price: 134900,
        rating: 4.9,
        imageUrl: phoneImages["iPhone 15 Pro Max"],
        affiliateLink: "https://www.amazon.in/apple-iphone-15-pro-max",
      },
      {
        name: "iPhone 16",
        brand: "Apple",
        specs: {
          processor: "A18 Bionic",
          ram: "8GB",
          storage: "128GB",
          display: "6.1 inch Super Retina XDR OLED",
          camera: "48MP + 12MP",
          frontCamera: "12MP",
          battery: "3561mAh",
          os: "iOS 18",
          network: "5G",
        },
        price: 79900,
        rating: 4.8,
        imageUrl: phoneImages["iPhone 16"],
        affiliateLink: "https://www.flipkart.com/apple-iphone-16",
      },
      {
        name: "iPhone 16 Plus",
        brand: "Apple",
        specs: {
          processor: "A18 Bionic",
          ram: "8GB",
          storage: "128GB",
          display: "6.7 inch Super Retina XDR OLED",
          camera: "48MP + 12MP",
          frontCamera: "12MP",
          battery: "4674mAh",
          os: "iOS 18",
          network: "5G",
        },
        price: 89900,
        rating: 4.8,
        imageUrl: "/assets/Apple-iPhone-16-hero-240909_inline.jpg.large.png",
        affiliateLink: "https://www.amazon.in/apple-iphone-16-plus",
      },
      {
        name: "iPhone 16 Pro",
        brand: "Apple",
        specs: {
          processor: "A18 Pro Bionic",
          ram: "8GB",
          storage: "128GB",
          display: "6.3 inch Super Retina XDR OLED",
          camera: "48MP + 48MP + 12MP",
          frontCamera: "12MP",
          battery: "3582mAh",
          os: "iOS 18",
          network: "5G",
        },
        price: 119900,
        rating: 4.9,
        imageUrl:
          "/assets/apple-iphone-16-pro-max-1tb-black-titanium-myx43.png",
        affiliateLink: "https://www.flipkart.com/apple-iphone-16-pro",
      },
      {
        name: "iPhone 16 Pro Max",
        brand: "Apple",
        specs: {
          processor: "A18 Pro Bionic",
          ram: "8GB",
          storage: "256GB",
          display: "6.9 inch Super Retina XDR OLED",
          camera: "48MP + 48MP + 12MP",
          frontCamera: "12MP",
          battery: "4685mAh",
          os: "iOS 18",
          network: "5G",
        },
        price: 144900,
        rating: 4.9,
        imageUrl:
          "/assets/apple-iphone-16-pro-max-1tb-black-titanium-myx43.png",
        affiliateLink: "https://www.amazon.in/apple-iphone-16-pro-max",
      },
      {
        name: "iPhone 13 Pro",
        brand: "Apple",
        specs: {
          processor: "A15 Bionic",
          ram: "6GB",
          storage: "256GB",
          display: "6.1 inch Super Retina XDR OLED",
          camera: "12MP + 12MP + 12MP",
          frontCamera: "12MP",
          battery: "3095mAh",
          os: "iOS 15",
          network: "5G",
        },
        price: 89900,
        rating: 4.7,
        imageUrl:
          "/assets/iphone-13-pro-256-gb-alpine-green-270849872-z3ndckg1.png",
        affiliateLink: "https://www.flipkart.com/apple-iphone-13-pro",
      },
      {
        name: "iPhone 14 Pro Max",
        brand: "Apple",
        specs: {
          processor: "A16 Bionic",
          ram: "6GB",
          storage: "128GB",
          display: "6.7 inch Super Retina XDR OLED",
          camera: "48MP + 12MP + 12MP",
          frontCamera: "12MP",
          battery: "4323mAh",
          os: "iOS 16",
          network: "5G",
        },
        price: 139900,
        rating: 4.8,
        imageUrl:
          "/assets/Apple-iPhone-14-Pro-iPhone-14-Pro-Max-deep-purple-220907-geo_inline.jpg.large.png",
        affiliateLink: "https://www.amazon.in/apple-iphone-14-pro-max",
      },


      {
        name: "Vivo X200 Pro",
        brand: "Vivo",
        specs: {
          processor: "MediaTek Dimensity 9400",
          ram: "16GB",
          storage: "512GB",
          display: "6.78 inch LTPO AMOLED",
          camera: "50MP + 50MP + 200MP",
          frontCamera: "32MP",
          battery: "6000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 94999,
        rating: 4.7,
        imageUrl:
          "/assets/Vivo-x200-pro-5g-titanium-grey-512gb-16gb-ram-Front-Back-View-Image.jpg",
        affiliateLink: "https://www.flipkart.com/vivo-x200-pro-5g",
      },
      {
        name: "Vivo X100 Pro",
        brand: "Vivo",
        specs: {
          processor: "MediaTek Dimensity 9300",
          ram: "16GB",
          storage: "512GB",
          display: "6.78 inch AMOLED",
          camera: "50MP + 50MP + 50MP",
          frontCamera: "32MP",
          battery: "5400mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 89899,
        rating: 4.7,
        imageUrl: "/assets/product_1.png",
        affiliateLink: "https://www.flipkart.com/vivo-x100-pro",
      },
      {
        name: "Vivo V30 Pro",
        brand: "Vivo",
        specs: {
          processor: "MediaTek Dimensity 8200",
          ram: "12GB",
          storage: "512GB",
          display: "6.78 inch AMOLED",
          camera: "50MP + 50MP + 50MP",
          frontCamera: "50MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 33800,
        rating: 4.5,
        imageUrl: "/assets/v30-5g-v2318-vivo-original-imagyzhhxumayhzw.png",
        affiliateLink: "https://www.flipkart.com/vivo-v30-pro-5g",
      },
      {
        name: "Vivo V30",
        brand: "Vivo",
        specs: {
          processor: "Snapdragon 7 Gen 3",
          ram: "8GB",
          storage: "256GB",
          display: "6.78 inch AMOLED",
          camera: "50MP + 50MP",
          frontCamera: "50MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 28999,
        rating: 4.4,
        imageUrl: "/assets/v30-5g-v2318-vivo-original-imagyzhhxumayhzw.png",
        affiliateLink: "https://www.amazon.in/vivo-v30-5g",
      },
      {
        name: "Vivo V40 Pro",
        brand: "Vivo",
        specs: {
          processor: "MediaTek Dimensity 9200+",
          ram: "12GB",
          storage: "256GB",
          display: "6.78 inch AMOLED",
          camera: "50MP + 50MP",
          frontCamera: "50MP",
          battery: "5500mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 49999,
        rating: 4.6,
        imageUrl: "/assets/product_2.png",
        affiliateLink: "https://www.flipkart.com/vivo-v40-pro",
      },
      {
        name: "Vivo V40",
        brand: "Vivo",
        specs: {
          processor: "Snapdragon 7 Gen 3",
          ram: "8GB",
          storage: "128GB",
          display: "6.78 inch AMOLED",
          camera: "50MP + 50MP",
          frontCamera: "50MP",
          battery: "5500mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 34999,
        rating: 4.5,
        imageUrl: "/assets/product_3.png",
        affiliateLink: "https://www.amazon.in/vivo-v40",
      },
      {
        name: "Vivo T3 Pro",
        brand: "Vivo",
        specs: {
          processor: "Snapdragon 7 Gen 3",
          ram: "8GB",
          storage: "256GB",
          display: "6.77 inch AMOLED",
          camera: "50MP + 8MP",
          frontCamera: "16MP",
          battery: "5500mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 24999,
        rating: 4.3,
        imageUrl: "/assets/product_4.png",
        affiliateLink: "https://www.flipkart.com/vivo-t3-pro",
      },
      {
        name: "Vivo T3",
        brand: "Vivo",
        specs: {
          processor: "MediaTek Dimensity 7200",
          ram: "8GB",
          storage: "128GB",
          display: "6.67 inch AMOLED",
          camera: "50MP + 2MP",
          frontCamera: "16MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 19999,
        rating: 4.2,
        imageUrl: "/assets/images.png",
        affiliateLink: "https://www.amazon.in/vivo-t3",
      },


      {
        name: "Nothing Phone (2)",
        brand: "Nothing",
        specs: {
          processor: "Snapdragon 8+ Gen 1",
          ram: "12GB",
          storage: "256GB",
          display: "6.7 inch LTPO OLED",
          camera: "50MP + 50MP",
          frontCamera: "32MP",
          battery: "4700mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 44999,
        rating: 4.4,
        imageUrl: "/assets/product_1.png",
        affiliateLink: "https://www.flipkart.com/nothing-phone-2",
      },
      {
        name: "Nothing Phone (2a)",
        brand: "Nothing",
        specs: {
          processor: "MediaTek Dimensity 7200 Pro",
          ram: "8GB",
          storage: "128GB",
          display: "6.7 inch AMOLED",
          camera: "50MP + 50MP",
          frontCamera: "32MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 25999,
        rating: 4.3,
        imageUrl: "/assets/product_2.png",
        affiliateLink: "https://www.amazon.in/nothing-phone-2a",
      },
      {
        name: "Nothing Phone (1)",
        brand: "Nothing",
        specs: {
          processor: "Snapdragon 778G+",
          ram: "8GB",
          storage: "128GB",
          display: "6.55 inch OLED",
          camera: "50MP + 50MP",
          frontCamera: "16MP",
          battery: "4500mAh",
          os: "Android 13",
          network: "5G",
        },
        price: 32999,
        rating: 4.2,
        imageUrl: "/assets/product_3.png",
        affiliateLink: "https://www.flipkart.com/nothing-phone-1",
      },


      {
        name: "OnePlus 12",
        brand: "OnePlus",
        specs: {
          processor: "Snapdragon 8 Gen 3",
          ram: "16GB",
          storage: "512GB",
          display: "6.82 inch LTPO AMOLED",
          camera: "50MP + 64MP + 48MP",
          frontCamera: "32MP",
          battery: "5400mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 64999,
        rating: 4.6,
        imageUrl: "/assets/product_4.png",
        affiliateLink: "https://www.amazon.in/oneplus-12-5g",
      },
      {
        name: "OnePlus 11 5G",
        brand: "OnePlus",
        specs: {
          processor: "Snapdragon 8 Gen 2",
          ram: "12GB",
          storage: "256GB",
          display: "6.7 inch LTPO AMOLED",
          camera: "50MP + 32MP + 48MP",
          frontCamera: "16MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 56999,
        rating: 4.5,
        imageUrl: "/assets/images.png",
        affiliateLink: "https://www.flipkart.com/oneplus-11-5g",
      },
      {
        name: "OnePlus Nord CE 4",
        brand: "OnePlus",
        specs: {
          processor: "Snapdragon 7 Gen 3",
          ram: "8GB",
          storage: "256GB",
          display: "6.7 inch AMOLED",
          camera: "50MP + 8MP",
          frontCamera: "16MP",
          battery: "5500mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 24999,
        rating: 4.3,
        imageUrl: "/assets/images-3.png",
        affiliateLink: "https://www.amazon.in/oneplus-nord-ce4",
      },
      {
        name: "OnePlus 12R",
        brand: "OnePlus",
        specs: {
          processor: "Snapdragon 8 Gen 2",
          ram: "8GB",
          storage: "128GB",
          display: "6.78 inch LTPO AMOLED",
          camera: "50MP + 8MP + 2MP",
          frontCamera: "16MP",
          battery: "5500mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 39999,
        rating: 4.4,
        imageUrl: "/assets/nn.jpg",
        affiliateLink: "https://www.flipkart.com/oneplus-12r",
      },
      {
        name: "OnePlus Nord 3 5G",
        brand: "OnePlus",
        specs: {
          processor: "MediaTek Dimensity 9000",
          ram: "16GB",
          storage: "256GB",
          display: "6.74 inch AMOLED",
          camera: "50MP + 8MP + 2MP",
          frontCamera: "16MP",
          battery: "5000mAh",
          os: "Android 13",
          network: "5G",
        },
        price: 33999,
        rating: 4.4,
        imageUrl: "/assets/hero_image.png",
        affiliateLink: "https://www.amazon.in/oneplus-nord-3-5g",
      },


      {
        name: "Samsung Galaxy S24 Ultra",
        brand: "Samsung",
        specs: {
          processor: "Snapdragon 8 Gen 3",
          ram: "12GB",
          storage: "512GB",
          display: "6.8 inch Dynamic AMOLED 2X",
          camera: "200MP + 50MP + 10MP + 12MP",
          frontCamera: "12MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 129999,
        rating: 4.7,
        imageUrl: "/assets/71d7rfSl0wL.png",
        affiliateLink: "https://www.flipkart.com/samsung-galaxy-s24-ultra",
      },
      {
        name: "Samsung Galaxy S24+",
        brand: "Samsung",
        specs: {
          processor: "Snapdragon 8 Gen 3",
          ram: "12GB",
          storage: "256GB",
          display: "6.7 inch Dynamic AMOLED 2X",
          camera: "50MP + 10MP + 12MP",
          frontCamera: "12MP",
          battery: "4900mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 99999,
        rating: 4.6,
        imageUrl: "/assets/718aEzLJKLL.png",
        affiliateLink: "https://www.amazon.in/samsung-galaxy-s24-plus",
      },
      {
        name: "Samsung Galaxy A55 5G",
        brand: "Samsung",
        specs: {
          processor: "Exynos 1480",
          ram: "8GB",
          storage: "128GB",
          display: "6.6 inch Super AMOLED",
          camera: "50MP + 12MP + 5MP",
          frontCamera: "32MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 39999,
        rating: 4.3,
        imageUrl: "/assets/717swzZZk5L.png",
        affiliateLink: "https://www.flipkart.com/samsung-galaxy-a55-5g",
      },
      {
        name: "Samsung Galaxy A35 5G",
        brand: "Samsung",
        specs: {
          processor: "Exynos 1380",
          ram: "8GB",
          storage: "128GB",
          display: "6.6 inch Super AMOLED",
          camera: "50MP + 8MP + 5MP",
          frontCamera: "13MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 30999,
        rating: 4.2,
        imageUrl:
          "/assets/in-galaxy-m-sm-m166plggins-front-light-green-thumb-545235495.png",
        affiliateLink: "https://www.amazon.in/samsung-galaxy-a35-5g",
      },
      {
        name: "Samsung Galaxy Z Flip 6",
        brand: "Samsung",
        specs: {
          processor: "Snapdragon 8 Gen 3",
          ram: "12GB",
          storage: "256GB",
          display: "6.7 inch Foldable Dynamic AMOLED 2X",
          camera: "50MP + 12MP",
          frontCamera: "10MP",
          battery: "4000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 109999,
        rating: 4.5,
        imageUrl:
          "/assets/in-galaxy-f-sm-e166pzkhins-sm-e---pzkdins-thumb-545373342.png",
        affiliateLink: "https://www.flipkart.com/samsung-galaxy-z-flip6",
      },
      {
        name: "Samsung Galaxy A06",
        brand: "Samsung",
        specs: {
          processor: "MediaTek Helio G85",
          ram: "4GB",
          storage: "64GB",
          display: "6.7 inch PLS LCD",
          camera: "50MP + 2MP",
          frontCamera: "8MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "4G",
        },
        price: 10499,
        rating: 4.0,
        imageUrl:
          "/assets/galaxy-a06-sm-a065flbdins-samsung-original-imah4az6d6xfjqqz.png",
        affiliateLink: "https://www.amazon.in/samsung-galaxy-a06",
      },


      {
        name: "iPhone 15",
        brand: "Apple",
        specs: {
          processor: "A16 Bionic",
          ram: "6GB",
          storage: "128GB",
          display: "6.1 inch Super Retina XDR OLED",
          camera: "48MP + 12MP",
          frontCamera: "12MP",
          battery: "3349mAh",
          os: "iOS 17",
          network: "5G",
        },
        price: 69900,
        rating: 4.8,
        imageUrl: "/assets/r1595_Purple_PDP_Image_Position-1A_Avail__en-IN.png",
        affiliateLink: "https://www.flipkart.com/apple-iphone-15",
      },
      {
        name: "iPhone 15 Plus",
        brand: "Apple",
        specs: {
          processor: "A16 Bionic",
          ram: "6GB",
          storage: "128GB",
          display: "6.7 inch Super Retina XDR OLED",
          camera: "48MP + 12MP",
          frontCamera: "12MP",
          battery: "4383mAh",
          os: "iOS 17",
          network: "5G",
        },
        price: 79900,
        rating: 4.7,
        imageUrl: "/assets/r1595_Purple_PDP_Image_Position-1A_Avail__en-IN.png",
        affiliateLink: "https://www.amazon.in/apple-iphone-15-plus",
      },
      {
        name: "iPhone 15 Pro",
        brand: "Apple",
        specs: {
          processor: "A17 Pro Bionic",
          ram: "8GB",
          storage: "128GB",
          display: "6.1 inch Super Retina XDR OLED",
          camera: "48MP + 12MP + 12MP",
          frontCamera: "12MP",
          battery: "3274mAh",
          os: "iOS 17",
          network: "5G",
        },
        price: 119900,
        rating: 4.9,
        imageUrl:
          "/assets/iphone-15-pro-max-256-gb-natural-titanium-272607387-rul0ytcs.png",
        affiliateLink: "https://www.flipkart.com/apple-iphone-15-pro",
      },
      {
        name: "iPhone 14",
        brand: "Apple",
        specs: {
          processor: "A15 Bionic",
          ram: "6GB",
          storage: "128GB",
          display: "6.1 inch Super Retina XDR OLED",
          camera: "12MP + 12MP",
          frontCamera: "12MP",
          battery: "3279mAh",
          os: "iOS 16",
          network: "5G",
        },
        price: 59900,
        rating: 4.6,
        imageUrl:
          "/assets/Apple_iphone13_hero_geo_09142021_inline.jpg.large.png",
        affiliateLink: "https://www.amazon.in/apple-iphone-14",
      },
      {
        name: "iPhone 14 Plus",
        brand: "Apple",
        specs: {
          processor: "A15 Bionic",
          ram: "6GB",
          storage: "128GB",
          display: "6.7 inch Super Retina XDR OLED",
          camera: "12MP + 12MP",
          frontCamera: "12MP",
          battery: "4325mAh",
          os: "iOS 16",
          network: "5G",
        },
        price: 69900,
        rating: 4.5,
        imageUrl:
          "/assets/Apple_iphone13_hero_geo_09142021_inline.jpg.large.png",
        affiliateLink: "https://www.flipkart.com/apple-iphone-14-plus",
      },
      {
        name: "iPhone 13",
        brand: "Apple",
        specs: {
          processor: "A15 Bionic",
          ram: "4GB",
          storage: "128GB",
          display: "6.1 inch Super Retina XDR OLED",
          camera: "12MP + 12MP",
          frontCamera: "12MP",
          battery: "3240mAh",
          os: "iOS 15",
          network: "5G",
        },
        price: 49900,
        rating: 4.5,
        imageUrl:
          "/assets/Apple_iphone13_hero_geo_09142021_inline.jpg.large.png",
        affiliateLink: "https://www.amazon.in/apple-iphone-13",
      },


      {
        name: "Xiaomi 14",
        brand: "Xiaomi",
        specs: {
          processor: "Snapdragon 8 Gen 3",
          ram: "12GB",
          storage: "512GB",
          display: "6.36 inch LTPO OLED",
          camera: "50MP + 50MP + 50MP",
          frontCamera: "32MP",
          battery: "4610mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 54999,
        rating: 4.4,
        imageUrl: "/assets/d9169f94917a9bb1de62d34fc43bb0ad.png",
        affiliateLink: "https://www.flipkart.com/xiaomi-14-5g",
      },
      {
        name: "Realme GT 6",
        brand: "Realme",
        specs: {
          processor: "Snapdragon 8s Gen 3",
          ram: "12GB",
          storage: "256GB",
          display: "6.78 inch LTPO AMOLED",
          camera: "50MP + 8MP + 2MP",
          frontCamera: "32MP",
          battery: "5500mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 40999,
        rating: 4.3,
        imageUrl: "/assets/ff8487e47efc45bb630a5620c2ca18e5.png_w860-h860.png",
        affiliateLink: "https://www.amazon.in/realme-gt-6-5g",
      },
      {
        name: "Oppo Reno 12 Pro",
        brand: "Oppo",
        specs: {
          processor: "MediaTek Dimensity 7300",
          ram: "12GB",
          storage: "256GB",
          display: "6.7 inch AMOLED",
          camera: "50MP + 8MP + 50MP",
          frontCamera: "50MP",
          battery: "5000mAh",
          os: "Android 14",
          network: "5G",
        },
        price: 36999,
        rating: 4.2,
        imageUrl: "/assets/d8ecae0f2ed29d943d83c44afac14873-2.png",
        affiliateLink: "https://www.flipkart.com/oppo-reno-12-pro-5g",
      },
    ],
  });

  console.log(
    "Database seeded successfully with real pricing and specifications!"
  );
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
  })
  .finally(() => {
    prisma.$disconnect();
  });
