const { PrismaClient } = require("../generated/prisma");
const prisma = new PrismaClient();

// Image mapping for phones to their local asset paths
const phoneImages = {
  "Samsung Galaxy S25 Ultra": "/assets/phones/samsung-galaxy-s25-ultra.jpg",
  "Samsung Galaxy Z Fold 6": "/assets/phones/samsung-galaxy-z-fold6.jpg",
  "Samsung Galaxy S24 Ultra": "/assets/phones/samsung-galaxy-s24-ultra.jpg",
  "Samsung Galaxy S24+": "/assets/phones/samsung-galaxy-s24-plus.jpg",
  "Samsung Galaxy A55 5G": "/assets/phones/samsung-galaxy-a55.jpg",
  "Samsung Galaxy A35 5G": "/assets/phones/samsung-galaxy-a35.jpg",
  "Samsung Galaxy Z Flip 6": "/assets/phones/samsung-galaxy-z-flip6.jpg",
  "Samsung Galaxy A06": "/assets/phones/samsung-galaxy-a06.jpg",
  "iPhone 15 Pro Max": "/assets/phones/iphone-15-pro-max.jpg",
  "iPhone 16": "/assets/phones/iphone-16.jpg",
  "iPhone 16 Plus": "/assets/phones/iphone-16-plus.jpg",
  "iPhone 16 Pro": "/assets/phones/iphone-16-pro.jpg",
  "iPhone 16 Pro Max": "/assets/phones/iphone-16-pro-max.jpg",
  "iPhone 13 Pro": "/assets/phones/iphone-13-pro.jpg",
  "iPhone 14 Pro Max": "/assets/phones/iphone-14-pro-max.jpg",
  "iPhone 15": "/assets/phones/iphone-15.jpg",
  "iPhone 15 Plus": "/assets/phones/iphone-15-plus.jpg",
  "iPhone 15 Pro": "/assets/phones/iphone-15-pro.jpg",
  "iPhone 14": "/assets/phones/iphone-14.jpg",
  "iPhone 14 Plus": "/assets/phones/iphone-14-plus.jpg",
  "iPhone 13": "/assets/phones/iphone-13.jpg",
  "Nothing Phone (2)": "/assets/phones/nothing-phone-2.jpg",
  "Nothing Phone (2a)": "/assets/phones/nothing-phone-2a.jpg",
  "Nothing Phone (1)": "/assets/phones/nothing-phone-1.jpg",
  "OnePlus 12": "/assets/phones/oneplus-12.jpg",
  "OnePlus 11 5G": "/assets/phones/oneplus-11.jpg",
  "OnePlus Nord CE 4": "/assets/phones/oneplus-nord-ce4.jpg",
  "OnePlus 12R": "/assets/phones/oneplus-12r.jpg",
  "OnePlus Nord 3 5G": "/assets/phones/oneplus-nord-3.jpg",
  "Vivo X200 Pro": "/assets/phones/vivo-x200-pro.jpg",
  "Vivo X100 Pro": "/assets/phones/vivo-x100-pro.jpg",
  "Vivo V30 Pro": "/assets/phones/vivo-v30-pro.jpg",
  "Vivo V30": "/assets/phones/vivo-v30.jpg",
  "Vivo V40 Pro": "/assets/phones/vivo-v40-pro.jpg",
  "Vivo V40": "/assets/phones/vivo-v40.jpg",
  "Vivo T3 Pro": "/assets/phones/vivo-t3-pro.jpg",
  "Vivo T3": "/assets/phones/vivo-t3.jpg",
  "Xiaomi 14": "/assets/phones/xiaomi-14.jpg",
  "Realme GT 6": "/assets/phones/realme-gt6.jpg",
  "Oppo Reno 12 Pro": "/assets/phones/oppo-reno12-pro.jpg",
};

async function main() {
  // Clear existing data first
  await prisma.product.deleteMany({});

  const phoneData = [
    // Samsung Galaxy Phones
    {
      name: "Samsung Galaxy S25 Ultra",
      brand: "Samsung",
      specs: {
        processor: "Snapdragon 8 Gen 3",
        ram: "12GB",
        storage: "512GB",
        display: "6.8 inch Dynamic AMOLED 2X",
        camera: "200MP + 50MP + 10MP + 12MP",
        frontCamera: "12MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 123499,
      rating: 4.8,
      affiliateLink: "https://www.flipkart.com/samsung-galaxy-s25-ultra",
    },
    {
      name: "Samsung Galaxy Z Fold 6",
      brand: "Samsung",
      specs: {
        processor: "Snapdragon 8 Gen 3",
        ram: "12GB",
        storage: "256GB",
        display: "7.6 inch Foldable Dynamic AMOLED 2X",
        camera: "50MP + 12MP + 10MP",
        frontCamera: "10MP + 4MP",
        battery: "4400mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 109785,
      rating: 4.7,
      affiliateLink: "https://www.amazon.in/samsung-galaxy-z-fold6",
    },
    {
      name: "Samsung Galaxy S24 Ultra",
      brand: "Samsung",
      specs: {
        processor: "Snapdragon 8 Gen 3",
        ram: "12GB",
        storage: "512GB",
        display: "6.8 inch Dynamic AMOLED 2X",
        camera: "200MP + 50MP + 10MP + 12MP",
        frontCamera: "12MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 129999,
      rating: 4.7,
      affiliateLink: "https://www.flipkart.com/samsung-galaxy-s24-ultra",
    },
    {
      name: "Samsung Galaxy S24+",
      brand: "Samsung",
      specs: {
        processor: "Snapdragon 8 Gen 3",
        ram: "12GB",
        storage: "256GB",
        display: "6.7 inch Dynamic AMOLED 2X",
        camera: "50MP + 10MP + 12MP",
        frontCamera: "12MP",
        battery: "4900mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 99999,
      rating: 4.6,
      affiliateLink: "https://www.amazon.in/samsung-galaxy-s24-plus",
    },
    {
      name: "Samsung Galaxy A55 5G",
      brand: "Samsung",
      specs: {
        processor: "Exynos 1480",
        ram: "8GB",
        storage: "128GB",
        display: "6.6 inch Super AMOLED",
        camera: "50MP + 12MP + 5MP",
        frontCamera: "32MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 39999,
      rating: 4.3,
      affiliateLink: "https://www.flipkart.com/samsung-galaxy-a55-5g",
    },
    {
      name: "Samsung Galaxy A35 5G",
      brand: "Samsung",
      specs: {
        processor: "Exynos 1380",
        ram: "8GB",
        storage: "128GB",
        display: "6.6 inch Super AMOLED",
        camera: "50MP + 8MP + 5MP",
        frontCamera: "13MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 30999,
      rating: 4.2,
      affiliateLink: "https://www.amazon.in/samsung-galaxy-a35-5g",
    },
    {
      name: "Samsung Galaxy Z Flip 6",
      brand: "Samsung",
      specs: {
        processor: "Snapdragon 8 Gen 3",
        ram: "12GB",
        storage: "256GB",
        display: "6.7 inch Foldable Dynamic AMOLED 2X",
        camera: "50MP + 12MP",
        frontCamera: "10MP",
        battery: "4000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 109999,
      rating: 4.5,
      affiliateLink: "https://www.flipkart.com/samsung-galaxy-z-flip6",
    },
    {
      name: "Samsung Galaxy A06",
      brand: "Samsung",
      specs: {
        processor: "MediaTek Helio G85",
        ram: "4GB",
        storage: "64GB",
        display: "6.7 inch PLS LCD",
        camera: "50MP + 2MP",
        frontCamera: "8MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "4G",
      },
      price: 10499,
      rating: 4.0,
      affiliateLink: "https://www.amazon.in/samsung-galaxy-a06",
    },

    // Apple iPhone Models
    {
      name: "iPhone 15 Pro Max",
      brand: "Apple",
      specs: {
        processor: "A17 Pro Bionic",
        ram: "8GB",
        storage: "256GB",
        display: "6.7 inch Super Retina XDR OLED",
        camera: "48MP + 12MP + 12MP",
        frontCamera: "12MP",
        battery: "4422mAh",
        os: "iOS 17",
        network: "5G",
      },
      price: 134900,
      rating: 4.9,
      affiliateLink: "https://www.amazon.in/apple-iphone-15-pro-max",
    },
    {
      name: "iPhone 16",
      brand: "Apple",
      specs: {
        processor: "A18 Bionic",
        ram: "8GB",
        storage: "128GB",
        display: "6.1 inch Super Retina XDR OLED",
        camera: "48MP + 12MP",
        frontCamera: "12MP",
        battery: "3561mAh",
        os: "iOS 18",
        network: "5G",
      },
      price: 79900,
      rating: 4.8,
      affiliateLink: "https://www.flipkart.com/apple-iphone-16",
    },
    {
      name: "iPhone 16 Plus",
      brand: "Apple",
      specs: {
        processor: "A18 Bionic",
        ram: "8GB",
        storage: "128GB",
        display: "6.7 inch Super Retina XDR OLED",
        camera: "48MP + 12MP",
        frontCamera: "12MP",
        battery: "4674mAh",
        os: "iOS 18",
        network: "5G",
      },
      price: 89900,
      rating: 4.8,
      affiliateLink: "https://www.amazon.in/apple-iphone-16-plus",
    },
    {
      name: "iPhone 16 Pro",
      brand: "Apple",
      specs: {
        processor: "A18 Pro Bionic",
        ram: "8GB",
        storage: "128GB",
        display: "6.3 inch Super Retina XDR OLED",
        camera: "48MP + 48MP + 12MP",
        frontCamera: "12MP",
        battery: "3582mAh",
        os: "iOS 18",
        network: "5G",
      },
      price: 119900,
      rating: 4.9,
      affiliateLink: "https://www.flipkart.com/apple-iphone-16-pro",
    },
    {
      name: "iPhone 16 Pro Max",
      brand: "Apple",
      specs: {
        processor: "A18 Pro Bionic",
        ram: "8GB",
        storage: "256GB",
        display: "6.9 inch Super Retina XDR OLED",
        camera: "48MP + 48MP + 12MP",
        frontCamera: "12MP",
        battery: "4685mAh",
        os: "iOS 18",
        network: "5G",
      },
      price: 144900,
      rating: 4.9,
      affiliateLink: "https://www.amazon.in/apple-iphone-16-pro-max",
    },
    {
      name: "iPhone 13 Pro",
      brand: "Apple",
      specs: {
        processor: "A15 Bionic",
        ram: "6GB",
        storage: "256GB",
        display: "6.1 inch Super Retina XDR OLED",
        camera: "12MP + 12MP + 12MP",
        frontCamera: "12MP",
        battery: "3095mAh",
        os: "iOS 15",
        network: "5G",
      },
      price: 89900,
      rating: 4.7,
      affiliateLink: "https://www.flipkart.com/apple-iphone-13-pro",
    },
    {
      name: "iPhone 14 Pro Max",
      brand: "Apple",
      specs: {
        processor: "A16 Bionic",
        ram: "6GB",
        storage: "128GB",
        display: "6.7 inch Super Retina XDR OLED",
        camera: "48MP + 12MP + 12MP",
        frontCamera: "12MP",
        battery: "4323mAh",
        os: "iOS 16",
        network: "5G",
      },
      price: 139900,
      rating: 4.8,
      affiliateLink: "https://www.amazon.in/apple-iphone-14-pro-max",
    },
    {
      name: "iPhone 15",
      brand: "Apple",
      specs: {
        processor: "A16 Bionic",
        ram: "6GB",
        storage: "128GB",
        display: "6.1 inch Super Retina XDR OLED",
        camera: "48MP + 12MP",
        frontCamera: "12MP",
        battery: "3349mAh",
        os: "iOS 17",
        network: "5G",
      },
      price: 69900,
      rating: 4.8,
      affiliateLink: "https://www.flipkart.com/apple-iphone-15",
    },
    {
      name: "iPhone 15 Plus",
      brand: "Apple",
      specs: {
        processor: "A16 Bionic",
        ram: "6GB",
        storage: "128GB",
        display: "6.7 inch Super Retina XDR OLED",
        camera: "48MP + 12MP",
        frontCamera: "12MP",
        battery: "4383mAh",
        os: "iOS 17",
        network: "5G",
      },
      price: 79900,
      rating: 4.7,
      affiliateLink: "https://www.amazon.in/apple-iphone-15-plus",
    },
    {
      name: "iPhone 15 Pro",
      brand: "Apple",
      specs: {
        processor: "A17 Pro Bionic",
        ram: "8GB",
        storage: "128GB",
        display: "6.1 inch Super Retina XDR OLED",
        camera: "48MP + 12MP + 12MP",
        frontCamera: "12MP",
        battery: "3274mAh",
        os: "iOS 17",
        network: "5G",
      },
      price: 119900,
      rating: 4.9,
      affiliateLink: "https://www.flipkart.com/apple-iphone-15-pro",
    },
    {
      name: "iPhone 14",
      brand: "Apple",
      specs: {
        processor: "A15 Bionic",
        ram: "6GB",
        storage: "128GB",
        display: "6.1 inch Super Retina XDR OLED",
        camera: "12MP + 12MP",
        frontCamera: "12MP",
        battery: "3279mAh",
        os: "iOS 16",
        network: "5G",
      },
      price: 59900,
      rating: 4.6,
      affiliateLink: "https://www.amazon.in/apple-iphone-14",
    },
    {
      name: "iPhone 14 Plus",
      brand: "Apple",
      specs: {
        processor: "A15 Bionic",
        ram: "6GB",
        storage: "128GB",
        display: "6.7 inch Super Retina XDR OLED",
        camera: "12MP + 12MP",
        frontCamera: "12MP",
        battery: "4325mAh",
        os: "iOS 16",
        network: "5G",
      },
      price: 69900,
      rating: 4.5,
      affiliateLink: "https://www.flipkart.com/apple-iphone-14-plus",
    },
    {
      name: "iPhone 13",
      brand: "Apple",
      specs: {
        processor: "A15 Bionic",
        ram: "4GB",
        storage: "128GB",
        display: "6.1 inch Super Retina XDR OLED",
        camera: "12MP + 12MP",
        frontCamera: "12MP",
        battery: "3240mAh",
        os: "iOS 15",
        network: "5G",
      },
      price: 49900,
      rating: 4.5,
      affiliateLink: "https://www.amazon.in/apple-iphone-13",
    },

    // Nothing Phones
    {
      name: "Nothing Phone (2)",
      brand: "Nothing",
      specs: {
        processor: "Snapdragon 8+ Gen 1",
        ram: "12GB",
        storage: "256GB",
        display: "6.7 inch LTPO OLED",
        camera: "50MP + 50MP",
        frontCamera: "32MP",
        battery: "4700mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 44999,
      rating: 4.4,
      affiliateLink: "https://www.flipkart.com/nothing-phone-2",
    },
    {
      name: "Nothing Phone (2a)",
      brand: "Nothing",
      specs: {
        processor: "MediaTek Dimensity 7200 Pro",
        ram: "8GB",
        storage: "128GB",
        display: "6.7 inch AMOLED",
        camera: "50MP + 50MP",
        frontCamera: "32MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 25999,
      rating: 4.3,
      affiliateLink: "https://www.amazon.in/nothing-phone-2a",
    },
    {
      name: "Nothing Phone (1)",
      brand: "Nothing",
      specs: {
        processor: "Snapdragon 778G+",
        ram: "8GB",
        storage: "128GB",
        display: "6.55 inch OLED",
        camera: "50MP + 50MP",
        frontCamera: "16MP",
        battery: "4500mAh",
        os: "Android 13",
        network: "5G",
      },
      price: 32999,
      rating: 4.2,
      affiliateLink: "https://www.flipkart.com/nothing-phone-1",
    },

    // OnePlus Phones
    {
      name: "OnePlus 12",
      brand: "OnePlus",
      specs: {
        processor: "Snapdragon 8 Gen 3",
        ram: "16GB",
        storage: "512GB",
        display: "6.82 inch LTPO AMOLED",
        camera: "50MP + 64MP + 48MP",
        frontCamera: "32MP",
        battery: "5400mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 64999,
      rating: 4.6,
      affiliateLink: "https://www.amazon.in/oneplus-12-5g",
    },
    {
      name: "OnePlus 11 5G",
      brand: "OnePlus",
      specs: {
        processor: "Snapdragon 8 Gen 2",
        ram: "12GB",
        storage: "256GB",
        display: "6.7 inch LTPO AMOLED",
        camera: "50MP + 32MP + 48MP",
        frontCamera: "16MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 56999,
      rating: 4.5,
      affiliateLink: "https://www.flipkart.com/oneplus-11-5g",
    },
    {
      name: "OnePlus Nord CE 4",
      brand: "OnePlus",
      specs: {
        processor: "Snapdragon 7 Gen 3",
        ram: "8GB",
        storage: "256GB",
        display: "6.7 inch AMOLED",
        camera: "50MP + 8MP",
        frontCamera: "16MP",
        battery: "5500mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 24999,
      rating: 4.3,
      affiliateLink: "https://www.amazon.in/oneplus-nord-ce4",
    },
    {
      name: "OnePlus 12R",
      brand: "OnePlus",
      specs: {
        processor: "Snapdragon 8 Gen 2",
        ram: "8GB",
        storage: "128GB",
        display: "6.78 inch LTPO AMOLED",
        camera: "50MP + 8MP + 2MP",
        frontCamera: "16MP",
        battery: "5500mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 39999,
      rating: 4.4,
      affiliateLink: "https://www.flipkart.com/oneplus-12r",
    },
    {
      name: "OnePlus Nord 3 5G",
      brand: "OnePlus",
      specs: {
        processor: "MediaTek Dimensity 9000",
        ram: "16GB",
        storage: "256GB",
        display: "6.74 inch AMOLED",
        camera: "50MP + 8MP + 2MP",
        frontCamera: "16MP",
        battery: "5000mAh",
        os: "Android 13",
        network: "5G",
      },
      price: 33999,
      rating: 4.4,
      affiliateLink: "https://www.amazon.in/oneplus-nord-3-5g",
    },

    // Vivo Phones
    {
      name: "Vivo X200 Pro",
      brand: "Vivo",
      specs: {
        processor: "MediaTek Dimensity 9400",
        ram: "16GB",
        storage: "512GB",
        display: "6.78 inch LTPO AMOLED",
        camera: "50MP + 50MP + 200MP",
        frontCamera: "32MP",
        battery: "6000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 94999,
      rating: 4.7,
      affiliateLink: "https://www.flipkart.com/vivo-x200-pro-5g",
    },
    {
      name: "Vivo X100 Pro",
      brand: "Vivo",
      specs: {
        processor: "MediaTek Dimensity 9300",
        ram: "16GB",
        storage: "512GB",
        display: "6.78 inch AMOLED",
        camera: "50MP + 50MP + 50MP",
        frontCamera: "32MP",
        battery: "5400mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 89899,
      rating: 4.7,
      affiliateLink: "https://www.flipkart.com/vivo-x100-pro",
    },
    {
      name: "Vivo V30 Pro",
      brand: "Vivo",
      specs: {
        processor: "MediaTek Dimensity 8200",
        ram: "12GB",
        storage: "512GB",
        display: "6.78 inch AMOLED",
        camera: "50MP + 50MP + 50MP",
        frontCamera: "50MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 33800,
      rating: 4.5,
      affiliateLink: "https://www.flipkart.com/vivo-v30-pro-5g",
    },
    {
      name: "Vivo V30",
      brand: "Vivo",
      specs: {
        processor: "Snapdragon 7 Gen 3",
        ram: "8GB",
        storage: "256GB",
        display: "6.78 inch AMOLED",
        camera: "50MP + 50MP",
        frontCamera: "50MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 28999,
      rating: 4.4,
      affiliateLink: "https://www.amazon.in/vivo-v30-5g",
    },
    {
      name: "Vivo V40 Pro",
      brand: "Vivo",
      specs: {
        processor: "MediaTek Dimensity 9200+",
        ram: "12GB",
        storage: "256GB",
        display: "6.78 inch AMOLED",
        camera: "50MP + 50MP",
        frontCamera: "50MP",
        battery: "5500mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 49999,
      rating: 4.6,
      affiliateLink: "https://www.flipkart.com/vivo-v40-pro",
    },
    {
      name: "Vivo V40",
      brand: "Vivo",
      specs: {
        processor: "Snapdragon 7 Gen 3",
        ram: "8GB",
        storage: "128GB",
        display: "6.78 inch AMOLED",
        camera: "50MP + 50MP",
        frontCamera: "50MP",
        battery: "5500mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 34999,
      rating: 4.5,
      affiliateLink: "https://www.amazon.in/vivo-v40",
    },
    {
      name: "Vivo T3 Pro",
      brand: "Vivo",
      specs: {
        processor: "Snapdragon 7 Gen 3",
        ram: "8GB",
        storage: "256GB",
        display: "6.77 inch AMOLED",
        camera: "50MP + 8MP",
        frontCamera: "16MP",
        battery: "5500mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 24999,
      rating: 4.3,
      affiliateLink: "https://www.flipkart.com/vivo-t3-pro",
    },
    {
      name: "Vivo T3",
      brand: "Vivo",
      specs: {
        processor: "MediaTek Dimensity 7200",
        ram: "8GB",
        storage: "128GB",
        display: "6.67 inch AMOLED",
        camera: "50MP + 2MP",
        frontCamera: "16MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 19999,
      rating: 4.2,
      affiliateLink: "https://www.amazon.in/vivo-t3",
    },

    // Additional Popular Brands from Amazon/Flipkart
    {
      name: "Xiaomi 14",
      brand: "Xiaomi",
      specs: {
        processor: "Snapdragon 8 Gen 3",
        ram: "12GB",
        storage: "512GB",
        display: "6.36 inch LTPO OLED",
        camera: "50MP + 50MP + 50MP",
        frontCamera: "32MP",
        battery: "4610mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 54999,
      rating: 4.4,
      affiliateLink: "https://www.flipkart.com/xiaomi-14-5g",
    },
    {
      name: "Realme GT 6",
      brand: "Realme",
      specs: {
        processor: "Snapdragon 8s Gen 3",
        ram: "12GB",
        storage: "256GB",
        display: "6.78 inch LTPO AMOLED",
        camera: "50MP + 8MP + 2MP",
        frontCamera: "32MP",
        battery: "5500mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 40999,
      rating: 4.3,
      affiliateLink: "https://www.amazon.in/realme-gt-6-5g",
    },
    {
      name: "Oppo Reno 12 Pro",
      brand: "Oppo",
      specs: {
        processor: "MediaTek Dimensity 7300",
        ram: "12GB",
        storage: "256GB",
        display: "6.7 inch AMOLED",
        camera: "50MP + 8MP + 50MP",
        frontCamera: "50MP",
        battery: "5000mAh",
        os: "Android 14",
        network: "5G",
      },
      price: 36999,
      rating: 4.2,
      affiliateLink: "https://www.flipkart.com/oppo-reno-12-pro-5g",
    },
  ];

  // Add imageUrl to each phone using the mapping
  const phoneDataWithImages = phoneData.map((phone) => ({
    ...phone,
    imageUrl:
      phoneImages[phone.name] ||
      phoneImages[phone.name.replace(" 5G", "")] ||
      "/assets/product_placeholder.png",
  }));

  await prisma.product.createMany({
    data: phoneDataWithImages,
  });

  console.log(
    "Database seeded successfully with correct phone images and pricing!"
  );
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
  })
  .finally(() => {
    prisma.$disconnect();
  });
